### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by Supriyo8799** [Wffv9FNa/Gelbooru-Favorite-Downloader#1]
This is not an issue but a request.
Can you create a script that can save/export the Gelbooru Favorites as CSV (Only the Post ID) and can later import it back to Gelbooru (Same or Different Account).

**Comment by Wffv9FNa** [comment]
Hi,
I've had a look at the [API documentation](https://gelbooru.com/index.php?page=wiki&s=view&id=18780) but it appears that it does not currently support functionality to favourite posts.
The most we could do at the moment is save the post IDs of a user's favourite posts to a JSON file.
If the API is updated in the future to support favouriting then it should be relatively simply to create a script which takes post IDs from a JSON and favourites them.
